// Canonical order with chapter counts (protestant 66-book set)
const BOOKS = [
  { index: 0, name: 'Genesis', chapters: 50 },
  { index: 1, name: 'Exodus', chapters: 40 },
  { index: 2, name: 'Leviticus', chapters: 27 },
  { index: 3, name: 'Numbers', chapters: 36 },
  { index: 4, name: 'Deuteronomy', chapters: 34 },
  { index: 5, name: 'Joshua', chapters: 24 },
  { index: 6, name: 'Judges', chapters: 21 },
  { index: 7, name: 'Ruth', chapters: 4 },
  { index: 8, name: '1 Samuel', chapters: 31 },
  { index: 9, name: '2 Samuel', chapters: 24 },
  { index: 10, name: '1 Kings', chapters: 22 },
  { index: 11, name: '2 Kings', chapters: 25 },
  { index: 12, name: '1 Chronicles', chapters: 29 },
  { index: 13, name: '2 Chronicles', chapters: 36 },
  { index: 14, name: 'Ezra', chapters: 10 },
  { index: 15, name: 'Nehemiah', chapters: 13 },
  { index: 16, name: 'Esther', chapters: 10 },
  { index: 17, name: 'Job', chapters: 42 },
  { index: 18, name: 'Psalm', chapters: 150 },
  { index: 19, name: 'Proverbs', chapters: 31 },
  { index: 20, name: 'Ecclesiastes', chapters: 12 },
  { index: 21, name: 'Song of Solomon', chapters: 8 },
  { index: 22, name: 'Isaiah', chapters: 66 },
  { index: 23, name: 'Jeremiah', chapters: 52 },
  { index: 24, name: 'Lamentations', chapters: 5 },
  { index: 25, name: 'Ezekiel', chapters: 48 },
  { index: 26, name: 'Daniel', chapters: 12 },
  { index: 27, name: 'Hosea', chapters: 14 },
  { index: 28, name: 'Joel', chapters: 3 },
  { index: 29, name: 'Amos', chapters: 9 },
  { index: 30, name: 'Obadiah', chapters: 1 },
  { index: 31, name: 'Jonah', chapters: 4 },
  { index: 32, name: 'Micah', chapters: 7 },
  { index: 33, name: 'Nahum', chapters: 3 },
  { index: 34, name: 'Habakkuk', chapters: 3 },
  { index: 35, name: 'Zephaniah', chapters: 3 },
  { index: 36, name: 'Haggai', chapters: 2 },
  { index: 37, name: 'Zechariah', chapters: 14 },
  { index: 38, name: 'Malachi', chapters: 4 },
  { index: 39, name: 'Matthew', chapters: 28 },
  { index: 40, name: 'Mark', chapters: 16 },
  { index: 41, name: 'Luke', chapters: 24 },
  { index: 42, name: 'John', chapters: 21 },
  { index: 43, name: 'Acts', chapters: 28 },
  { index: 44, name: 'Romans', chapters: 16 },
  { index: 45, name: '1 Corinthians', chapters: 16 },
  { index: 46, name: '2 Corinthians', chapters: 13 },
  { index: 47, name: 'Galatians', chapters: 6 },
  { index: 48, name: 'Ephesians', chapters: 6 },
  { index: 49, name: 'Philippians', chapters: 4 },
  { index: 50, name: 'Colossians', chapters: 4 },
  { index: 51, name: '1 Thessalonians', chapters: 5 },
  { index: 52, name: '2 Thessalonians', chapters: 3 },
  { index: 53, name: '1 Timothy', chapters: 6 },
  { index: 54, name: '2 Timothy', chapters: 4 },
  { index: 55, name: 'Titus', chapters: 3 },
  { index: 56, name: 'Philemon', chapters: 1 },
  { index: 57, name: 'Hebrews', chapters: 13 },
  { index: 58, name: 'James', chapters: 5 },
  { index: 59, name: '1 Peter', chapters: 5 },
  { index: 60, name: '2 Peter', chapters: 3 },
  { index: 61, name: '1 John', chapters: 5 },
  { index: 62, name: '2 John', chapters: 1 },
  { index: 63, name: '3 John', chapters: 1 },
  { index: 64, name: 'Jude', chapters: 1 },
  { index: 65, name: 'Revelation', chapters: 22 },
];