// Lexicon entries with Strong's where applicable (offline demo subset)
window.LEXICON = {
  // Genesis 1 Hebrew terms
  'beginning': { headword: 'רֵאשִׁית (rēʾšît)', translit: 'reshit', lang: 'hebrew', strongs: 'H7225', glosses: ['beginning', 'first'], morph: 'Noun feminine', senses: ['initial point', 'first fruits (metaphor)'], refs: ['Genesis 1:1'] },
  'god': { headword: 'אֱלֹהִים (\'ĕlōhîm)', translit: 'elohim', lang: 'hebrew', strongs: 'H430', glosses: ['God', 'gods'], morph: 'Noun plural (majestic plural)', senses: ['the true God', 'divine beings (contextual)'], refs: ['Genesis 1:1'] },
  'created': { headword: 'בָּרָא (bārāʾ)', translit: 'bara', lang: 'hebrew', strongs: 'H1234', glosses: ['created', 'made'], morph: 'Verb qal perfect', senses: ['divine creation', 'bringing into existence'], refs: ['Genesis 1:1'] },
  'heaven': { headword: 'שָׁמַיִם (šāmayim)', translit: 'shamayim', lang: 'hebrew', strongs: 'H8064', glosses: ['heaven', 'sky'], morph: 'Noun dual', senses: ['physical sky', 'spiritual realm'], refs: ['Genesis 1:1'] },
  'earth': { headword: 'אֶרֶץ (\'ereṣ)', translit: 'eretz', lang: 'hebrew', strongs: 'H776', glosses: ['earth', 'land'], morph: 'Noun feminine', senses: ['planet earth', 'ground', 'territory'], refs: ['Genesis 1:1'] },
  'light': { headword: 'אוֹר (\'ôr)', translit: 'or', lang: 'hebrew', strongs: 'H216', glosses: ['light'], morph: 'Noun masculine', senses: ['physical light', 'metaphorical enlightenment'], refs: ['Genesis 1:3'] },
  'darkness': { headword: 'חֹשֶׁךְ (ḥōšeḵ)', translit: 'choshek', lang: 'hebrew', strongs: 'H2822', glosses: ['darkness'], morph: 'Noun masculine', senses: ['absence of light', 'spiritual darkness'], refs: ['Genesis 1:2'] },
  'spirit': { headword: 'רוּחַ (rûaḥ)', translit: 'ruach', lang: 'hebrew', strongs: 'H7307', glosses: ['spirit', 'breath', 'wind'], morph: 'Noun feminine', senses: ['Holy Spirit', 'human spirit', 'wind'], refs: ['Genesis 1:2'] },
  'water': { headword: 'מַיִם (mayim)', translit: 'mayim', lang: 'hebrew', strongs: 'H4325', glosses: ['water'], morph: 'Noun dual', senses: ['literal water', 'chaos waters'], refs: ['Genesis 1:2'] },
  'good': { headword: 'טוֹב (ṭôḇ)', translit: 'tov', lang: 'hebrew', strongs: 'H2896', glosses: ['good', 'pleasant'], morph: 'Adjective masculine', senses: ['morally good', 'beneficial'], refs: ['Genesis 1:4'] },
  
  // More Hebrew terms
  'lord': { headword: 'יְהוָה (YHWH)', translit: 'Yahweh', lang: 'hebrew', strongs: 'H3068', glosses: ['LORD', 'Yahweh'], morph: 'Proper noun', senses: ['covenant name of God'], refs: ['Genesis 2:4'] },
  'man': { headword: 'אָדָם (\'āḏām)', translit: 'adam', lang: 'hebrew', strongs: 'H120', glosses: ['man', 'mankind'], morph: 'Noun masculine', senses: ['human being', 'Adam'], refs: ['Genesis 1:27'] },
  'image': { headword: 'צֶלֶם (ṣelem)', translit: 'tselem', lang: 'hebrew', strongs: 'H6754', glosses: ['image', 'likeness'], morph: 'Noun masculine', senses: ['divine image', 'representation'], refs: ['Genesis 1:27'] },
  'soul': { headword: 'נֶפֶשׁ (nepeš)', translit: 'nephesh', lang: 'hebrew', strongs: 'H5315', glosses: ['soul', 'life', 'being'], morph: 'Noun feminine', senses: ['living being', 'inner life'], refs: ['Genesis 2:7'] },
  'covenant': { headword: 'בְּרִית (bᵊrîṯ)', translit: 'berith', lang: 'hebrew', strongs: 'H1285', glosses: ['covenant', 'treaty'], morph: 'Noun feminine', senses: ['divine covenant', 'agreement'], refs: ['Genesis 9:9'] },
  'love': { headword: 'אַהֲבָה (\'ahăḇāh)', translit: 'ahavah', lang: 'hebrew', strongs: 'H160', glosses: ['love'], morph: 'Noun feminine', senses: ['divine love', 'human love'], refs: ['Deuteronomy 6:5'] },
  'holy': { headword: 'קָדוֹשׁ (qāḏôš)', translit: 'qadosh', lang: 'hebrew', strongs: 'H6918', glosses: ['holy', 'sacred'], morph: 'Adjective masculine', senses: ['set apart', 'sacred'], refs: ['Leviticus 11:44'] },
  'righteousness': { headword: 'צְדָקָה (ṣᵊḏāqāh)', translit: 'tsedaqah', lang: 'hebrew', strongs: 'H6666', glosses: ['righteousness', 'justice'], morph: 'Noun feminine', senses: ['moral righteousness', 'justice'], refs: ['Psalm 23:3'] },
  'peace': { headword: 'שָׁלוֹם (šālôm)', translit: 'shalom', lang: 'hebrew', strongs: 'H7965', glosses: ['peace', 'wholeness'], morph: 'Noun masculine', senses: ['peace', 'completeness', 'welfare'], refs: ['Numbers 6:26'] },
  'sin': { headword: 'חַטָּאת (ḥaṭṭāʾṯ)', translit: 'chattat', lang: 'hebrew', strongs: 'H2403', glosses: ['sin', 'sin offering'], morph: 'Noun feminine', senses: ['missing the mark', 'transgression'], refs: ['Genesis 4:7'] },
  'salvation': { headword: 'יְשׁוּעָה (yᵊšûʿāh)', translit: 'yeshuah', lang: 'hebrew', strongs: 'H3444', glosses: ['salvation', 'deliverance'], morph: 'Noun feminine', senses: ['divine rescue', 'deliverance'], refs: ['Psalm 3:8'] },
  'worship': { headword: 'שָׁחָה (šāḥāh)', translit: 'shachah', lang: 'hebrew', strongs: 'H7812', glosses: ['worship', 'bow down'], morph: 'Verb qal', senses: ['prostrate worship', 'reverence'], refs: ['Genesis 22:5'] },
  'faith': { headword: 'אֱמוּנָה (\'ĕmûnāh)', translit: 'emunah', lang: 'hebrew', strongs: 'H530', glosses: ['faith', 'faithfulness'], morph: 'Noun feminine', senses: ['steadfastness', 'reliability'], refs: ['Habakkuk 2:4'] },
  'mercy': { headword: 'חֶסֶד (ḥeseḏ)', translit: 'chesed', lang: 'hebrew', strongs: 'H2617', glosses: ['mercy', 'lovingkindness'], morph: 'Noun masculine', senses: ['covenant love', 'loyal love'], refs: ['Psalm 23:6'] },
  'truth': { headword: 'אֱמֶת (\'emeṯ)', translit: 'emet', lang: 'hebrew', strongs: 'H571', glosses: ['truth', 'faithfulness'], morph: 'Noun feminine', senses: ['reliability', 'truth'], refs: ['Psalm 25:5'] },
  'wisdom': { headword: 'חָכְמָה (ḥāḵᵊmāh)', translit: 'chokmah', lang: 'hebrew', strongs: 'H2451', glosses: ['wisdom', 'skill'], morph: 'Noun feminine', senses: ['divine wisdom', 'practical skill'], refs: ['Proverbs 1:7'] },
  'fear': { headword: 'יִרְאָה (yirʾāh)', translit: 'yirah', lang: 'hebrew', strongs: 'H3374', glosses: ['fear', 'reverence'], morph: 'Noun feminine', senses: ['reverential awe', 'fear'], refs: ['Proverbs 1:7'] },

  // Additional Hebrew theological terms
  'king': { headword: 'מֶלֶךְ (meleḵ)', translit: 'melekh', lang: 'hebrew', strongs: 'H4428', glosses: ['king'], morph: 'Noun masculine', senses: ['royal ruler', 'sovereign'], refs: ['1 Samuel 8:5'] },
  'kingdom': { headword: 'מַלְכוּת (malḵûṯ)', translit: 'malkhut', lang: 'hebrew', strongs: 'H4438', glosses: ['kingdom', 'reign'], morph: 'Noun feminine', senses: ['royal dominion', 'sovereignty'], refs: ['Psalm 103:19'] },
  'prophet': { headword: 'נָבִיא (nāḇîʾ)', translit: 'navi', lang: 'hebrew', strongs: 'H5030', glosses: ['prophet'], morph: 'Noun masculine', senses: ['spokesman for God', 'seer'], refs: ['Deuteronomy 18:18'] },
  'priest': { headword: 'כֹּהֵן (kōhēn)', translit: 'kohen', lang: 'hebrew', strongs: 'H3548', glosses: ['priest'], morph: 'Noun masculine', senses: ['mediator', 'religious leader'], refs: ['Leviticus 1:7'] },
  'sacrifice': { headword: 'זֶבַח (zeḇaḥ)', translit: 'zevach', lang: 'hebrew', strongs: 'H2077', glosses: ['sacrifice'], morph: 'Noun masculine', senses: ['offering', 'slaughter for worship'], refs: ['Leviticus 1:2'] },
  'altar': { headword: 'מִזְבֵּחַ (mizᵊbēaḥ)', translit: 'mizbeach', lang: 'hebrew', strongs: 'H4196', glosses: ['altar'], morph: 'Noun masculine', senses: ['place of sacrifice', 'worship platform'], refs: ['Genesis 8:20'] },
  'temple': { headword: 'בַּיִת (bayiṯ)', translit: 'bayit', lang: 'hebrew', strongs: 'H1004', glosses: ['house', 'temple'], morph: 'Noun masculine', senses: ['dwelling', 'sacred building'], refs: ['1 Kings 6:1'] },
  'glory': { headword: 'כָּבוֹד (kāḇôḏ)', translit: 'kavod', lang: 'hebrew', strongs: 'H3519', glosses: ['glory', 'honor'], morph: 'Noun masculine', senses: ['divine splendor', 'weightiness'], refs: ['Exodus 24:16'] },
  'blessing': { headword: 'בְּרָכָה (bᵊrāḵāh)', translit: 'berakhah', lang: 'hebrew', strongs: 'H1293', glosses: ['blessing'], morph: 'Noun feminine', senses: ['divine favor', 'benediction'], refs: ['Genesis 12:2'] },
  'promise': { headword: 'דָּבָר (dāḇār)', translit: 'davar', lang: 'hebrew', strongs: 'H1697', glosses: ['word', 'promise'], morph: 'Noun masculine', senses: ['spoken word', 'divine promise'], refs: ['Numbers 23:19'] },
  'angel': { headword: 'מַלְאָךְ (malʾāḵ)', translit: 'malakh', lang: 'hebrew', strongs: 'H4397', glosses: ['angel', 'messenger'], morph: 'Noun masculine', senses: ['divine messenger', 'heavenly being'], refs: ['Genesis 16:7'] },
  'sword': { headword: 'חֶרֶב (ḥereḇ)', translit: 'cherev', lang: 'hebrew', strongs: 'H2719', glosses: ['sword'], morph: 'Noun feminine', senses: ['weapon', 'instrument of judgment'], refs: ['Genesis 3:24'] },
  'shield': { headword: 'מָגֵן (māḡēn)', translit: 'magen', lang: 'hebrew', strongs: 'H4043', glosses: ['shield'], morph: 'Noun masculine', senses: ['protection', 'defense'], refs: ['Psalm 3:3'] },
  'shepherd': { headword: 'רֹעֶה (rōʿeh)', translit: 'roeh', lang: 'hebrew', strongs: 'H7462', glosses: ['shepherd'], morph: 'Noun masculine', senses: ['pastor', 'protector'], refs: ['Psalm 23:1'] },
  'rock': { headword: 'צוּר (ṣûr)', translit: 'tsur', lang: 'hebrew', strongs: 'H6697', glosses: ['rock'], morph: 'Noun masculine', senses: ['stone', 'fortress', 'strength'], refs: ['Deuteronomy 32:4'] },
  'fire': { headword: 'אֵשׁ (\'ēš)', translit: 'esh', lang: 'hebrew', strongs: 'H784', glosses: ['fire'], morph: 'Noun feminine', senses: ['flame', 'divine presence'], refs: ['Exodus 3:2'] },
  'blood': { headword: 'דָּם (dām)', translit: 'dam', lang: 'hebrew', strongs: 'H1818', glosses: ['blood'], morph: 'Noun masculine', senses: ['life force', 'atonement'], refs: ['Leviticus 17:11'] },

  // Job creatures
  'behemoth': { headword: 'בְּהֵמוֹת (behemoth)', translit: 'behemoth', lang: 'hebrew', strongs: 'H930', glosses: ['beast, Behemoth'], morph: 'Noun plural intensive', senses: ['colossal land creature'], refs: ['Job 40:15–24'] },
  'leviathan': { headword: 'לִוְיָתָן (liwyāṯān)', translit: 'livyatan', lang: 'hebrew', strongs: 'H3882', glosses: ['Leviathan'], morph: 'Noun masculine', senses: ['sea creature/chaos monster symbol'], refs: ['Job 41'] },

  // Greek New Testament terms
  'loved': { headword: 'ἠγάπησεν (ēgapēsen)', translit: 'egapesen', lang: 'greek', strongs: 'G25', glosses: ['loved'], morph: 'Verb aorist active', senses: ['divine love', 'sacrificial love'], refs: ['John 3:16'] },
  'world': { headword: 'κόσμος (kosmos)', translit: 'kosmos', lang: 'greek', strongs: 'G2889', glosses: ['world', 'universe'], morph: 'Noun masculine', senses: ['created order', 'humanity in rebellion'], refs: ['John 3:16'] },
  'born': { headword: 'γεννηθῇ (gennēthē)', translit: 'gennethe', lang: 'greek', strongs: 'G1080', glosses: ['born', 'begotten'], morph: 'Verb aorist passive subjunctive', senses: ['physical birth', 'spiritual regeneration'], refs: ['John 3:3'] },
  'believe': { headword: 'πιστεύω (pisteuō)', translit: 'pisteuo', lang: 'greek', strongs: 'G4100', glosses: ['believe', 'trust'], morph: 'Verb present active', senses: ['have faith in', 'trust'], refs: ['John 3:16'] },
  'eternal': { headword: 'αἰώνιος (aiōnios)', translit: 'aionios', lang: 'greek', strongs: 'G166', glosses: ['eternal', 'everlasting'], morph: 'Adjective', senses: ['without end', 'age-lasting'], refs: ['John 3:16'] },
  'life': { headword: 'ζωή (zōē)', translit: 'zoe', lang: 'greek', strongs: 'G2222', glosses: ['life'], morph: 'Noun feminine', senses: ['spiritual life', 'divine life'], refs: ['John 3:16'] },
  'son': { headword: 'υἱός (huios)', translit: 'huios', lang: 'greek', strongs: 'G5207', glosses: ['son'], morph: 'Noun masculine', senses: ['male offspring', 'Son of God'], refs: ['John 3:16'] },
  'gave': { headword: 'ἔδωκεν (edōken)', translit: 'edoken', lang: 'greek', strongs: 'G1325', glosses: ['gave', 'granted'], morph: 'Verb aorist active', senses: ['bestowed', 'granted'], refs: ['John 3:16'] },
  'only': { headword: 'μονογενής (monogenēs)', translit: 'monogenes', lang: 'greek', strongs: 'G3439', glosses: ['only', 'unique'], morph: 'Adjective', senses: ['one and only', 'unique'], refs: ['John 3:16'] },
  'perish': { headword: 'ἀπόλλυμι (apollumi)', translit: 'apollumi', lang: 'greek', strongs: 'G622', glosses: ['perish', 'destroy'], morph: 'Verb aorist middle subjunctive', senses: ['be destroyed', 'be lost'], refs: ['John 3:16'] },
  'whosoever': { headword: 'πᾶς (pas)', translit: 'pas', lang: 'greek', strongs: 'G3956', glosses: ['all', 'every', 'whosoever'], morph: 'Adjective', senses: ['each', 'every one'], refs: ['John 3:16'] },
  'sent': { headword: 'ἀπέστειλεν (apesteilen)', translit: 'apesteilen', lang: 'greek', strongs: 'G649', glosses: ['sent'], morph: 'Verb aorist active', senses: ['commissioned', 'sent forth'], refs: ['John 3:17'] },
  'condemn': { headword: 'κρίνω (krinō)', translit: 'krino', lang: 'greek', strongs: 'G2919', glosses: ['judge', 'condemn'], morph: 'Verb aorist active subjunctive', senses: ['pass judgment', 'condemn'], refs: ['John 3:17'] },
  'saved': { headword: 'σώζω (sōzō)', translit: 'sozo', lang: 'greek', strongs: 'G4982', glosses: ['save', 'deliver'], morph: 'Verb aorist passive subjunctive', senses: ['rescue', 'preserve'], refs: ['John 3:17'] },
  'jesus': { headword: 'Ἰησοῦς (Iēsous)', translit: 'Iesous', lang: 'greek', strongs: 'G2424', glosses: ['Jesus'], morph: 'Proper noun', senses: ['Jesus Christ', 'Savior'], refs: ['John 3:2'] },
  'christ': { headword: 'Χριστός (Christos)', translit: 'Christos', lang: 'greek', strongs: 'G5547', glosses: ['Christ', 'Messiah'], morph: 'Proper noun', senses: ['the Anointed One'], refs: ['Matthew 1:1'] },
  'grace': { headword: 'χάρις (charis)', translit: 'charis', lang: 'greek', strongs: 'G5485', glosses: ['grace', 'favor'], morph: 'Noun feminine', senses: ['unmerited favor', 'divine grace'], refs: ['Ephesians 2:8'] },
  'works': { headword: 'ἔργον (ergon)', translit: 'ergon', lang: 'greek', strongs: 'G2041', glosses: ['work', 'deed'], morph: 'Noun neuter', senses: ['action', 'accomplishment'], refs: ['Ephesians 2:9'] },
  'church': { headword: 'ἐκκλησία (ekklēsia)', translit: 'ekklesia', lang: 'greek', strongs: 'G1577', glosses: ['church', 'assembly'], morph: 'Noun feminine', senses: ['called-out ones', 'congregation'], refs: ['Matthew 16:18'] },
  'apostle': { headword: 'ἀπόστολος (apostolos)', translit: 'apostolos', lang: 'greek', strongs: 'G652', glosses: ['apostle', 'messenger'], morph: 'Noun masculine', senses: ['sent one', 'missionary'], refs: ['1 Corinthians 1:1'] },
  'gospel': { headword: 'εὐαγγέλιον (euangelion)', translit: 'euangelion', lang: 'greek', strongs: 'G2098', glosses: ['gospel', 'good news'], morph: 'Noun neuter', senses: ['good tidings', 'message of salvation'], refs: ['Romans 1:16'] },
  'power': { headword: 'δύναμις (dunamis)', translit: 'dunamis', lang: 'greek', strongs: 'G1411', glosses: ['power', 'strength'], morph: 'Noun feminine', senses: ['miraculous power', 'ability'], refs: ['Romans 1:16'] },
  'righteousness': { headword: 'δικαιοσύνη (dikaiosunē)', translit: 'dikaiosune', lang: 'greek', strongs: 'G1343', glosses: ['righteousness'], morph: 'Noun feminine', senses: ['right standing', 'justice'], refs: ['Romans 1:17'] },
  'revelation': { headword: 'ἀποκάλυψις (apokalupsis)', translit: 'apokalupsis', lang: 'greek', strongs: 'G602', glosses: ['revelation', 'unveiling'], morph: 'Noun feminine', senses: ['disclosure', 'revelation'], refs: ['Romans 1:17'] },
  'wrath': { headword: 'ὀργή (orgē)', translit: 'orge', lang: 'greek', strongs: 'G3709', glosses: ['wrath', 'anger'], morph: 'Noun feminine', senses: ['divine anger', 'judgment'], refs: ['Romans 1:18'] },
  'creation': { headword: 'κτίσις (ktisis)', translit: 'ktisis', lang: 'greek', strongs: 'G2937', glosses: ['creation', 'creature'], morph: 'Noun feminine', senses: ['act of creating', 'created thing'], refs: ['Romans 1:20'] },
  'invisible': { headword: 'ἀόρατος (aoratos)', translit: 'aoratos', lang: 'greek', strongs: 'G517', glosses: ['invisible', 'unseen'], morph: 'Adjective', senses: ['not visible', 'spiritual'], refs: ['Romans 1:20'] },
  'godhead': { headword: 'θειότης (theiotēs)', translit: 'theiotes', lang: 'greek', strongs: 'G2305', glosses: ['godhead', 'divinity'], morph: 'Noun feminine', senses: ['divine nature'], refs: ['Romans 1:20'] },
  'excuse': { headword: 'ἀναπολόγητος (anapologētos)', translit: 'anapologetos', lang: 'greek', strongs: 'G379', glosses: ['without excuse'], morph: 'Adjective', senses: ['inexcusable'], refs: ['Romans 1:20'] },

  // Additional Greek theological terms
  'word': { headword: 'λόγος (logos)', translit: 'logos', lang: 'greek', strongs: 'G3056', glosses: ['word', 'reason'], morph: 'Noun masculine', senses: ['divine word', 'rational principle'], refs: ['John 1:1'] },
  'flesh': { headword: 'σάρξ (sarx)', translit: 'sarx', lang: 'greek', strongs: 'G4561', glosses: ['flesh'], morph: 'Noun feminine', senses: ['physical body', 'human nature'], refs: ['John 1:14'] },
  'glory': { headword: 'δόξα (doxa)', translit: 'doxa', lang: 'greek', strongs: 'G1391', glosses: ['glory', 'honor'], morph: 'Noun feminine', senses: ['divine splendor', 'reputation'], refs: ['John 1:14'] },
  'witness': { headword: 'μαρτυρία (martyria)', translit: 'martyria', lang: 'greek', strongs: 'G3141', glosses: ['witness', 'testimony'], morph: 'Noun feminine', senses: ['testimony', 'evidence'], refs: ['John 1:7'] },
  'baptism': { headword: 'βάπτισμα (baptisma)', translit: 'baptisma', lang: 'greek', strongs: 'G908', glosses: ['baptism'], morph: 'Noun neuter', senses: ['immersion', 'ritual cleansing'], refs: ['Matthew 3:7'] },
  'repentance': { headword: 'μετάνοια (metanoia)', translit: 'metanoia', lang: 'greek', strongs: 'G3341', glosses: ['repentance'], morph: 'Noun feminine', senses: ['change of mind', 'turning from sin'], refs: ['Matthew 3:8'] },
  'forgiveness': { headword: 'ἄφεσις (aphesis)', translit: 'aphesis', lang: 'greek', strongs: 'G859', glosses: ['forgiveness', 'remission'], morph: 'Noun feminine', senses: ['release', 'pardon'], refs: ['Matthew 26:28'] },
  'resurrection': { headword: 'ἀνάστασις (anastasis)', translit: 'anastasis', lang: 'greek', strongs: 'G386', glosses: ['resurrection'], morph: 'Noun feminine', senses: ['rising up', 'restoration to life'], refs: ['Matthew 22:23'] },
  'cross': { headword: 'σταυρός (stauros)', translit: 'stauros', lang: 'greek', strongs: 'G4716', glosses: ['cross'], morph: 'Noun masculine', senses: ['execution stake', 'symbol of sacrifice'], refs: ['Matthew 27:32'] },
  'covenant': { headword: 'διαθήκη (diathēkē)', translit: 'diatheke', lang: 'greek', strongs: 'G1242', glosses: ['covenant', 'testament'], morph: 'Noun feminine', senses: ['agreement', 'will'], refs: ['Matthew 26:28'] },
  'disciple': { headword: 'μαθητής (mathētēs)', translit: 'mathetes', lang: 'greek', strongs: 'G3101', glosses: ['disciple', 'learner'], morph: 'Noun masculine', senses: ['student', 'follower'], refs: ['Matthew 5:1'] },
  'prayer': { headword: 'προσευχή (proseuchē)', translit: 'proseuche', lang: 'greek', strongs: 'G4335', glosses: ['prayer'], morph: 'Noun feminine', senses: ['petition to God', 'worship'], refs: ['Matthew 6:5'] },
  'temptation': { headword: 'πειρασμός (peirasmos)', translit: 'peirasmos', lang: 'greek', strongs: 'G3986', glosses: ['temptation', 'trial'], morph: 'Noun masculine', senses: ['testing', 'enticement to sin'], refs: ['Matthew 6:13'] },
  'evil': { headword: 'πονηρός (ponēros)', translit: 'poneros', lang: 'greek', strongs: 'G4190', glosses: ['evil', 'wicked'], morph: 'Adjective', senses: ['morally corrupt', 'harmful'], refs: ['Matthew 6:13'] },
  'parable': { headword: 'παραβολή (parabolē)', translit: 'parabole', lang: 'greek', strongs: 'G3850', glosses: ['parable'], morph: 'Noun feminine', senses: ['comparison', 'illustrative story'], refs: ['Matthew 13:3'] },
  'miracle': { headword: 'σημεῖον (sēmeion)', translit: 'semeion', lang: 'greek', strongs: 'G4592', glosses: ['sign', 'miracle'], morph: 'Noun neuter', senses: ['wonder', 'divine attestation'], refs: ['John 2:11'] },
  'heal': { headword: 'θεραπεύω (therapeuō)', translit: 'therapeuo', lang: 'greek', strongs: 'G2323', glosses: ['heal', 'cure'], morph: 'Verb', senses: ['restore to health', 'serve'], refs: ['Matthew 4:23'] },
  'demon': { headword: 'δαιμόνιον (daimonion)', translit: 'daimonion', lang: 'greek', strongs: 'G1140', glosses: ['demon'], morph: 'Noun neuter', senses: ['evil spirit', 'unclean spirit'], refs: ['Matthew 7:22'] },
  'scripture': { headword: 'γραφή (graphē)', translit: 'graphe', lang: 'greek', strongs: 'G1124', glosses: ['scripture', 'writing'], morph: 'Noun feminine', senses: ['sacred writing', 'biblical text'], refs: ['Matthew 21:42'] },
  'law': { headword: 'νόμος (nomos)', translit: 'nomos', lang: 'greek', strongs: 'G3551', glosses: ['law'], morph: 'Noun masculine', senses: ['divine law', 'Torah'], refs: ['Matthew 5:17'] },
  'commandment': { headword: 'ἐντολή (entolē)', translit: 'entole', lang: 'greek', strongs: 'G1785', glosses: ['commandment'], morph: 'Noun feminine', senses: ['precept', 'divine order'], refs: ['Matthew 5:19'] },
  'blessed': { headword: 'μακάριος (makarios)', translit: 'makarios', lang: 'greek', strongs: 'G3107', glosses: ['blessed', 'happy'], morph: 'Adjective', senses: ['divinely favored', 'fortunate'], refs: ['Matthew 5:3'] },
  'servant': { headword: 'δοῦλος (doulos)', translit: 'doulos', lang: 'greek', strongs: 'G1401', glosses: ['servant', 'slave'], morph: 'Noun masculine', senses: ['bondservant', 'devoted follower'], refs: ['Matthew 10:24'] },
  'master': { headword: 'διδάσκαλος (didaskalos)', translit: 'didaskalos', lang: 'greek', strongs: 'G1320', glosses: ['teacher', 'master'], morph: 'Noun masculine', senses: ['instructor', 'rabbi'], refs: ['Matthew 8:19'] }
};